# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ec674a830766a80f688ae2e738fbd765426623196b7e4f457ae83504e5ffa4458002ff31d7630c6cea2123fd5a41f27ef8da2d54379a15f04573886982a1428

test:
  secret_key_base: 46c857243c5e5f28315ae83bf8512afc9506ac82d607172f0db1dc2947c22d4565d933574bcbcb9a3da315b0ccd2c6a7440a8d1fbefc47757e98cae960df695d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
