# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c52c008dd536dfd08e2b0c92c027b0521f37c832ede4aa625746f37ffc267c527be5974ff764a90160c9e73d774810694abaa7312ee7ebffade1f2fb402c440

test:
  secret_key_base: 9bc0e20c3ad5304be04b754c73d5ebb3e4299761d638aab57660d7e5df5f6bb4ef7cebafe3ee58bf9965186687d48db2913e8964bf47ec285b737fafb70bf1bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
