# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c77361c1e4b7977501ab20c874b4d08ae6363ab19ca03719175d2b48fd2d9aa00d6348dd8e6945ead176490abf62736b617d7275ebef45297cf07ba9a236b0fd

test:
  secret_key_base: a19e8ea5d84d61a86a9eccececa9f9c5ca8ce2a38bc009125ee32638bdb525046f6ff33af63d14b365268c1316409e8c3a1643c1cdb72f83c54440045081f55c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
