# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a97e2a454430c273a96610f835b565203d9341ac9ec94ff3d5cf07ddd2cb15e804da218abe50d83e81f7eb320c64026154b97ed9a4d852db242313efc72957da

test:
  secret_key_base: 15e72dab0a2726f89767870c1b0b0d02f4626675744efa653b861f50d675490826169ad00b5b32370e09f2c412d5bf79bdc1768bb5ed92177ad80093d58374b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
